file_dir: '/media/kini/B0E4EF45E4EF0C82/PythonFolder/parsing/VTB/json_excel/test'


file_name: '11111'
base_system_source: '11111'
base_system_target: '1642_19 Озеро данных'
mapping_version: 1.0


docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=2893063076'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 11111
loadType: 'Scd0Append'
database: 'test'
topic: 'test'
colsToHash: ['']