'dir': 'D:\Projects\VTB\Mapping_files\1963\test'
'subo_name': '1816 Полномочия представителя ФЛ'
'id_ris': '1816'
'mapping_version': '2.0'
'loadType': 'Scd0Appenddddd'
'database': 'windows'
'topic': 'new'
'system_target': '1642_19 Озеро данных'
'developer': 'Kamenev Ilya'
'docs': 'windows'






