file_dir: 'D:\Projects\VTB\Mapping_files\1498\test'


file_name: '1816 Полномочия представителя ФЛ'
base_system_source: '1816 Полномочия представителя ФЛ'
base_system_target: '1642_19 Озеро данных'
mapping_version: 1.0


docs: 'https://'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1816
loadType: 'Scd0Append'
database: 'test'
topic: 'test'
colsToHash: ['']