'base_system_source': '1816 Полномочия представителя ФЛ'
'base_system_target': '1642_19 Озеро данных'
'database': 'tttttt'
'developer': 'Kamenev Ilya'
'docs': 'httpsdfdfsdf'
'file_dir': '/media/kini/B0E4EF45E4EF0C82/PythonFolder/parsing/VTB/json_excel/sales'
'file_name': '1816 Полномочия представителя ФЛ'
'id_is': '1816'
'loadType': 'Scd0Appenddddd'
'mapping_version': '2.0'
'topic': 'new'
