'database': 'nsm'
'developer': 'Kamenev Ilyaaaaa'
'docs': 'https://testtestest'
'file_dir': 'D:/Projects/VTB/Mapping_files/1387'
'id_ris': '1963'
'loadType': 'Scd0Appendpartition'
'mapping_version': '2.0'
'subo_name': '1963 test'
'system_target': '1642_19 Озеро данных'
'topic': 'nsm'
