file_dir: 'D:\Projects\VTB\Mapping_files\1387'
old_mapping_flag: 'no'

file_name: 'Переводы'
base_system_source: 'Переводы'
base_system_target: '1642_19 Озеро данных'
tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']

docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=2850376288'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1387
loadType: 'Scd0Append'
database: 'trns'
topic: "trns"
colsToHash: ['']