file_dir: '/media/kini/B0E4EF45E4EF0C82/PythonFolder/parsing/VTB/json_excel/1593'
old_mapping_flag: 'no'

file_name: 'ису'
base_system_source: 'ису'
base_system_target: '1642_19 Озеро данных'
tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']

docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=2863043647'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1593
loadType: 'Scd0Append'
database: 'isra'
topic: "isramra"
colsToHash: ['']