file_dir: 'D:\Projects\VTB\Mapping_files\1516\'

file_name: 'Нотификации_ФЛ'
base_system_source: 'Нотификации_ФЛ'
base_system_target: '1642_19 Озеро данных'
tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']

docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=2708461914'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1364
loadType: 'Scd0Append'
database: 'nsm'
topic: "nsm"
colsToHash: ['']