'database': 'test'
'developer': 'Kamenev Ilya'
'docs': 'https://test'
'file_dir': 'D:\Projects\VTB\Mapping_files\Mappng_form\test'
'id_ris': '1816'
'loadType': 'Scd0Append'
'mapping_version': '1.0'
'subo_name': '1816 test'
'system_target': '1642_19 Озеро данных'
'topic': 'test'
