'database': 'bprb'
'developer': 'Kamenev Ilya'
'docs': 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=3179850346'
'file_dir': 'D:\Projects\VTB\Mapping_files\1756'
'id_ris': '1756'
'loadType': 'Scd0Append'
'mapping_version': '1.0'
'subo_name': '1756 Бонусный процессор'
'system_target': '1642_19 Озеро данных'
'topic': 'bprb'
