file_dir: 'D:\Projects\VTB\Mapping_files\1612_2\Json'
check_dir: 'D:\Projects\VTB\Mapping_files\1987'

old_mapping_flag: 'no'
file_name: 'МаркетингЮЛ'
base_system_source: 'МаркетингЮЛ'
base_system_target: '1642_19 Озеро данных'
mapping_version: 1.0

tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']
docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=1903683597'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1612_2
loadType: 'Scd0Append'
database: 'sgbp_fnsi_ptd'
topic: "sgbp_fnsi_ptd"
colsToHash: ['']