'database': 'test'
'developer': 'Kamenev Ilya'
'docs': 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=3179850346'
'file_dir': '/media/kini/B0E4EF45E4EF0C82/PythonFolder/parsing/VTB/json_excel/sales'
'id_ris': '1756'
'loadType': 'Scd0Append'
'mapping_version': '1.0'
'subo_name': '1756 Бонусный процессор'
'system_target': '1642_19 Озеро данных'
'topic': 'test'
