'database': 'nsm'
'developer': 'Kamenev Ilya'
'docs': 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=3152161229'
'file_dir': 'D:\Projects\VTB\Mappng_form\test'
'id_ris': '1516'
'loadType': 'Scd0Append'
'mapping_version': '1.0'
'subo_name': '1516 Управление услугой нотификации ФЛ'
'system_target': '1642_19 Озеро данных'
'topic': 'nsm'
