'database': 'nsm'
'developer': 'Kamenev Ilya'
'docs': 'https://testtestest'
'file_dir': 'D:/Projects/VTB/Mapping_files/1816'
'id_ris': '1516'
'loadType': 'Scd0Append'
'mapping_version': '2.0'
'subo_name': '1516 test'
'system_target': '1642_19 Озеро данных'
'topic': 'nsm'
