file_dir: 'D:\Projects\VTB\Mapping_files\1447_8\'
old_mapping_flag: 'no'

file_name: 'Сервис_привлечения_и_удержания_VIP_и_Привилегия'
base_system_source: 'Сервис_привлечения_и_удержания_VIP_и_Привилегия'
base_system_target: '1642_19 Озеро данных'
tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']

docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=1089443760'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1447_8
loadType: 'Scd0Append'
database: 'tbcv'
topic: "tbcvsofk"
colsToHash: ['']