file_dir: '/media/kini/B0E4EF45E4EF0C82/PythonFolder/parsing/VTB/json_excel/new/'
old_mapping_flag: ''

file_name: 'Тест'
base_system_source: 'Тест'
base_system_target: '1642_19 Озеро данных'
tech_fields: ['changeid', 'changetype', 'changetimestamp', 'hdp_processed_dttm']

docs: 'https://wiki.corp.dev.vtb/pages/viewpage.action?pageId=1214863127'
developer: 'Kamenev Ilya'
etl_schema: 'etl_schema'
id_is: 1111
loadType: 'Scd0Append'
database: 'test'
topic: "test"
colsToHash: ['']